version: '3'
services:
  lnd:
    build: ./lnd
    image: cherijs/lnd:latest
    container_name: alice
    restart: always
    ports:
      - "10010:10009"
      - "9010:9735"
    volumes:
      - ./lnd/lnd.conf:/root/.lnd/lnd.conf
      - bitcoin:/root/.bitcoin/
      - lnd_alice:/root/.lnd/ # data persistence
    command:
      --noseedbackup
      --debuglevel=debug
      --maxpendingchannels=10
      --rpclisten=0.0.0.0:10009
      --color=#4126a7
      --alias=Alice
      --bitcoin.active
      --bitcoin.testnet
      --bitcoin.node=bitcoind
      --bitcoind.rpchost=btc
      --bitcoind.rpcuser=test
      --bitcoind.rpcpass=test
      --bitcoind.zmqpubrawblock=tcp://btc:28332
      --bitcoind.zmqpubrawtx=tcp://btc:28333


volumes:
  bitcoin:
    driver: local
    driver_opts:
      type: none
      device: "/Users/cherijs/.docker_volumes/.bitcoin"
      o: bind
  lnd_alice:
    driver: local
    driver_opts:
      type: none
      device: "/Users/cherijs/.docker_volumes/simnet/alice"
      o: bind